# Configuration for https://travis-ci.org/

language: go
go_import_path: blitiri.com.ar/go/chasquid
dist: trusty
sudo: false

go:
    # Check against the version in Debian stable.
    - 1.11.x
    - stable
    - master

env:
  # Enable Go modules explicitly on Go 1.11.
  # Some packages update in backwards-incompatible ways assuming Go modules
  # are in use, which can break the build unexpectedly.
  # We can remove this once we no longer support Go 1.11, as it is the default
  # in the newer versions.
  - GO111MODULE=on

# This is needed because the repository has a Makefile, so travis won't invoke
# "go get" by default.
install:
    - go get blitiri.com.ar/go/chasquid
    - go get blitiri.com.ar/go/chasquid/cmd/chasquid-util
    - go get blitiri.com.ar/go/chasquid/cmd/mda-lmtp
    - go get blitiri.com.ar/go/chasquid/cmd/smtp-check
    - go get blitiri.com.ar/go/chasquid/cmd/spf-check

script:
    - make all
    - go test ./...
    - go test -race ./...

notifications:
    email:
        on_success: change
        on_failure: always
    irc:
        channels:
          - "ircs://chat.freenode.net:7070/#chasquid"
        use_notice: true
        on_success: change
        on_failure: always
